#include "platform.h"
#include "dvdwriter.h"
#include "xmlreader.h"

namespace param
{
    bool noWarns = false;
    bool noIsoGen = false;
    bool overwrite = false;
    bool quietMode = false;

    fs::path xmlFile;
    fs::path isoFile;
    fs::path lbaFile;
    fs::path lbaHeadFile;
    fs::path licenseFile;
    std::optional<std::string> volid_override;
};

static void WriteLogLBA(iso::DirTree *dirTree)
{
    unique_file fp = OpenScopedFile(param::lbaFile, "w");
    if (fp != nullptr)
    {
        fprintf(fp.get(), "File LBA log generated by MKPS2ISO v" VERSION "\n\n");
        fprintf(fp.get(), "Image file: \"%s\"\n", param::isoFile.string().c_str());

        fprintf(fp.get(), "\nFile System:\n\n");
        fprintf(fp.get(), "   Type   |              Name              | Length |  LBA  |   Bytes   |   Source File\n\n");

        dirTree->SortDirectoryEntries(true);
        dirTree->OutputLBAlisting(fp.get(), 0);
        dirTree->SortDirectoryEntries();

        if (!param::quietMode)
            printf("Wrote file LBA log \"%s\"\n\n", param::lbaFile.string().c_str());
    }
    else if (!param::quietMode)
    {
        printf("Failed to write LBA log \"%s\"!\n\n", param::lbaFile.string().c_str());
    }
}

static void WriteLogHead(iso::DirTree *dirTree)
{
    unique_file fp = OpenScopedFile(param::lbaHeadFile, "w");
    if (fp != nullptr)
    {
        fprintf(fp.get(), "#ifndef _ISO_FILES\n");
        fprintf(fp.get(), "#define _ISO_FILES\n\n");

        dirTree->SortDirectoryEntries(true);
        dirTree->OutputHeaderListing(fp.get(), "<ROOT>");
        dirTree->SortDirectoryEntries();
        fprintf(fp.get(), "#endif\n");

        if (!param::quietMode)
            printf("Wrote file LBA listing header \"%s\"\n\n", param::lbaHeadFile.string().c_str());
    }
    else if (!param::quietMode)
    {
        printf("Failed to write LBA listing header \"%s\"!\n\n", param::lbaHeadFile.string().c_str());
    }
}

static bool BuildISO(xml::Reader &xml)
{
    iso::IDENTIFIERS isoIdentifiers{};
    if (xml.ReadHeaders(isoIdentifiers) == nullptr)
        return false;

    if (param::volid_override)
        isoIdentifiers.VolumeID = param::volid_override->c_str();

    // Print out identifiers if present
    if (!param::quietMode)
    {
        printf("Building ISO Image: \"%s\"\n\n", param::isoFile.string().c_str());

        printf("Identifiers:\n");

        if (isoIdentifiers.SystemID != nullptr)
            printf("  System ID         : %s\n", isoIdentifiers.SystemID);
        else
            printf("  System ID         : %s%s\n", isoIdentifiers.SystemID = "PLAYSTATION", " (default)"); // Set default identifier if not present

        if (isoIdentifiers.VolumeID != nullptr)
            printf("  Volume ID         : %s\n", isoIdentifiers.VolumeID);

        if (isoIdentifiers.VolumeSet != nullptr)
            printf("  Volume Set ID     : %s\n", isoIdentifiers.VolumeSet);

        if (isoIdentifiers.Publisher != nullptr)
            printf("  Publisher ID      : %s\n", isoIdentifiers.Publisher);

        if (isoIdentifiers.DataPreparer != nullptr)
            printf("  Data Preparer ID  : %s\n", isoIdentifiers.DataPreparer);

        if (isoIdentifiers.Application != nullptr)
            printf("  Application ID    : %s\n", isoIdentifiers.Application);
        else
            printf("  Application ID    : %s%s\n", isoIdentifiers.Application = "PLAYSTATION", " (default)"); // Set default identifier if not present

        if (isoIdentifiers.Copyright != nullptr)
            printf("  Copyright ID      : %s\n", isoIdentifiers.Copyright);

        if (isoIdentifiers.CreationDate != nullptr)
            printf("  Creation Date     : %s\n", isoIdentifiers.CreationDate);

        if (isoIdentifiers.ModificationDate != nullptr)
            printf("  Modification Date : %s\n", isoIdentifiers.ModificationDate);

        printf("\n");
    }

    // If empty, blank sectors will be written.
    if (!param::licenseFile.empty())
    {
        if (!param::quietMode)
            printf("License file: \"%s\"\n\n", param::licenseFile.string().c_str());

        int64_t licenseSize = GetSize(param::licenseFile);
        if (licenseSize != sizeof(ISO_LICENSE) && !param::noWarns)
            printf("WARNING: Specified license file may not be of correct format.\n");
    }

    // Parse directory entries in the <directory_tree> element
    if (!param::quietMode)
        printf("Parsing directory tree...\n");

    // Generate file system
    std::list<Entry> entries;
    iso::DirTree *dirTree = xml.ReadDirTree(entries, isoIdentifiers.CreationDate);
    if (dirTree == nullptr)
        return EXIT_FAILURE;

    // Sort entries
    dirTree->PartitionEntries();
    dirTree->SortDirectoryEntries();

    // Calculate tree LBAs
    const uint32_t pathTableLen      = dirTree->CalculatePathTableLen(entries.front());
    const uint32_t isoRootLBA        = layout::LBA_TABLE_START + (GetSizeInSectors(pathTableLen) * 4);
    const uint32_t partitionStartLBA = dirTree->CalculateDirRecordLBA(isoRootLBA);
    const uint32_t fidRootLBA        = partitionStartLBA + GetSizeInSectors(sizeof(layout::FSD));
    const uint32_t icbRootLBA        = dirTree->CalculateFileIdDescLBA(fidRootLBA);
    const uint32_t dataStartLBA      = dirTree->CalculateInfCtrlBlockLBA(icbRootLBA);
    const uint32_t totalLenLBA       = AlignTo<16>(dirTree->CalculateFileTreeLBA(dataStartLBA) + GetSizeInSectors(sizeof(anchorVolDescPtr)));

    if (!param::quietMode)
    {
        printf("  Files Total: %u\n", dirTree->GetFileCount());
        printf("  Directories: %u\n", dirTree->GetDirCount());
        printf("  Total file system size: %u bytes (%u sectors)\n\n", DVD_SECTOR_SIZE * totalLenLBA, totalLenLBA);
    }

    if (!param::lbaFile.empty())
        WriteLogLBA(dirTree);

    if (!param::lbaHeadFile.empty())
        WriteLogHead(dirTree);

    if (param::noIsoGen)
    {
        if (!param::quietMode)
            printf("Skipped image generation.\n");
        return true;
    }

    if (!param::overwrite && !param::noWarns && GetSize(param::isoFile) >= 0)
    {
        printf("WARNING: ISO image already exists, overwrite? <Y/n> ");
        uint8_t key = getchar();
        if (std::tolower(key) == 'n')
            return false;
        printf("\n");
    }

    // Create ISO image for writing
    if (!dvd::writer->Create(param::isoFile, totalLenLBA))
    {
        printf("ERROR: Cannot open or create output image file.\n");
        return false;
    }

    // Write files
    if (!param::quietMode)
        printf("Repacking...\n");

    // Copy the files into the disc image
    dirTree->WriteFiles();

    if (!param::quietMode)
        printf("\n");

    // Write license data
    if (!param::licenseFile.empty())
    {
        unique_file fp = OpenScopedFile(param::licenseFile, "rb");
        if (fp == nullptr)
            goto write_blank_license;

        auto license = std::make_unique<ISO_LICENSE>();
        if (fread(license->data, sizeof(license->data), 1, fp.get()) != 1)
            goto write_blank_license;

        if (!param::quietMode)
            printf("Writing license data...");

        iso::WriteLicenseData(license->data);

        if (!param::quietMode)
            printf("Ok.\n");
    }
    else
    {
    write_blank_license:
        auto appBlankSectors = dvd::writer->GetSectorView(0, 14);
        appBlankSectors->WriteBlankSectors(14);
    }

    // Master Disc sectors
    auto masterSectors = dvd::writer->GetSectorView(14, 2);
    masterSectors->WriteBlankSectors(2); // TODO: conditionally write actual MD data

    // Write file system
    if (!param::quietMode)
        printf("Writing descriptors... ");

    // Write ISO descriptors
    dirTree->WriteIsoDescriptors(totalLenLBA, isoIdentifiers);
    dirTree->WriteDirectoryRecords();

    // Write Extended Area Descriptors
    iso::WriteExtendedDescriptors();

    // Write UDF descriptors
    uint32_t partitionSize = totalLenLBA - GetSizeInSectors(sizeof(anchorVolDescPtr)) - partitionStartLBA;
    iso::WriteUdfDescriptors(partitionStartLBA, partitionSize, isoIdentifiers, layout::LBA_UDF_MAIN);
    iso::WriteUdfDescriptors(partitionStartLBA, partitionSize, isoIdentifiers, layout::LBA_UDF_RSRV);
    iso::WriteLviDescriptors(dirTree, partitionSize, isoIdentifiers);
    iso::WriteAnchorDescriptor(partitionStartLBA + partitionSize);

    // Write file system descriptors to finish the image
    dirTree->WriteInfoCtrlBlocks(partitionStartLBA);
    dirTree->WriteFileSetDescriptors(partitionStartLBA, isoIdentifiers);
    dirTree->WriteFileIdDescriptors(partitionStartLBA);

    if (!param::quietMode)
        printf("Ok.\n\n");

    // Close ISO writer
    dvd::writer->Close();

    if (!param::quietMode)
        printf("Image built successfully.\n");

    return true;
}

int Main(int argc, char *argv[])
{
    constexpr const char *HELP_TEXT =
        "Usage: mkps2iso [options] <input>\n\n"
        "  <input>\t\tAny XML project file defining the disc layout to build.\n\n"
        "Options:\n"
        "  -h|--help\t\tShows this help text\n"
        "  -q|--quiet\t\tQuiet mode (suppress all but warnings and errors)\n"
        "  -w|--warns\t\tSuppress all warnings (can be used along with -q)\n"
        "  -n|--noisogen\t\tDo not generate ISO, but calculate file LBA locations (for use with --lba or --lbahead)\n"
        "  -l|--lba <file>\tGenerate a log of file LBA locations in disc image\n"
        "  -lh|--lbahead <file>\tGenerate a C header of file LBA locations in disc image\n"
        "  -o|--output <file>\tSpecify output file (overrides image_name attribute)\n"
        "  -L|--license <file>\tSpecify license file (overrides file attribute)\n"
        "  -lb|--label\t\tSpecify volume ID (overrides volume element)\n"
        "  -y\t\t\tAlways overwrite ISO image files\n";

    constexpr const char *VERSION_TEXT =
        "MKPS2ISO " VERSION " - PlayStation 2 Image Maker\n"
        "Get the latest version at https://github.com/N4gtan/mkps2iso\n\n";

    if (argc == 1)
    {
        printf(VERSION_TEXT);
        printf(HELP_TEXT);
        return EXIT_SUCCESS;
    }

    bool OutputOverride = false;
    // Parse arguments
    for (char **args = argv + 1; *args != nullptr; args++)
    {
        // Is it a switch?
        if ((*args)[0] == '-')
        {
            if (ParseArgument(args, "h", "help"))
            {
                printf(VERSION_TEXT);
                printf(HELP_TEXT);
                return EXIT_SUCCESS;
            }
            if (ParseArgument(args, "q", "quiet"))
            {
                param::quietMode = true;
                continue;
            }
            if (ParseArgument(args, "w", "warns"))
            {
                param::noWarns = true;
                continue;
            }
            if (ParseArgument(args, "n", "noisogen"))
            {
                param::noIsoGen = true;
                continue;
            }
            if (ParseArgument(args, "y"))
            {
                param::overwrite = true;
                continue;
            }
            if (auto lbaFile = ParsePathArgument(args, "l", "lba"); lbaFile.has_value())
            {
                if (CompareICase(lbaFile->extension().string(), ".xml"))
                {
                    args--;
                    param::lbaFile = lbaFile->stem() += "_LBA.txt";
                    continue;
                }
                param::lbaFile = lbaFile->lexically_normal();
                continue;
            }
            if (auto lbaHead = ParsePathArgument(args, "lh", "lbahead"); lbaHead.has_value())
            {
                if (CompareICase(lbaHead->extension().string(), ".xml"))
                {
                    args--;
                    param::lbaHeadFile = lbaHead->stem() += "_LBA.h";
                    continue;
                }
                param::lbaHeadFile = lbaHead->lexically_normal();
                continue;
            }
            if (auto output = ParsePathArgument(args, "o", "output"); output.has_value())
            {
                param::isoFile = output->lexically_normal();
                OutputOverride = true;
                continue;
            }
            if (auto output = ParsePathArgument(args, "L", "license"); output.has_value())
            {
                param::licenseFile = output->lexically_normal();
                continue;
            }
            if (auto label = ParseStringArgument(args, "lb", "label"); label.has_value())
            {
                param::volid_override = label;
                continue;
            }

            // If we reach this point, an unknown parameter was passed
            printf("Unknown parameter: %s\n", *args);
            return EXIT_FAILURE;
        }

        if (param::xmlFile.empty())
        {
            param::xmlFile = fs::path(*args).lexically_normal().lexically_proximate(fs::current_path());
        }
        else
        {
            printf("Only one XML script is supported. (use an XML with multiple <iso_project> elements instead)\n");
            return EXIT_FAILURE;
        }
    }

    if (param::xmlFile.empty())
    {
        printf("No XML script specified.\n");
        return EXIT_FAILURE;
    }

    if (!param::quietMode)
        printf(VERSION_TEXT);

    if (param::lbaFile == "-l" || param::lbaFile == "--lba")
        param::lbaFile = param::xmlFile.stem() += "_LBA.txt";

    if (param::lbaHeadFile == "-lh" || param::lbaHeadFile == "--lbahead")
        param::lbaHeadFile = param::xmlFile.stem() += "_LBA.h";

    // Initialize xml reader
    xml::Reader xml;

    // Initialize dvd writer
    dvd::writer = std::make_unique<dvd::IsoWriter>();

    int imagesCount = 0;
    // Build loop for XML scripts with multiple <iso_project> elements
    while (xml.NextProjectElement() != nullptr)
    {
        imagesCount++;
        if (imagesCount > 1 && OutputOverride)
        {
            printf("ERROR: -o switch cannot be used in a multi-disc ISO project.\n");
            return EXIT_FAILURE;
        }

        if (!BuildISO(xml))
            return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
