#include "platform.h"
#include "dvdwriter.h"
#include "xmlreader.h"

namespace param
{
    bool noWarns = false;
    bool noIsoGen = false;
    bool overwrite = false;
    bool quietMode = false;

    fs::path xmlFile;
    fs::path isoFile;
    fs::path lbaFile;
    fs::path lbaHeadFile;
    fs::path logoRawFile;
    std::optional<std::string> volid_override;
};

static void WriteLogLBA(const std::list<std::tuple<std::list<Entry>, uint32_t, uint32_t>> &layers)
{
    unique_file fp = OpenScopedFile(param::lbaFile, "w");
    if (fp != nullptr)
    {
        fprintf(fp.get(), "File LBA log generated by MKPS2ISO v" VERSION "\n\n");
        fprintf(fp.get(), "Image file: \"%s\"\n", param::isoFile.string().c_str());

        fprintf(fp.get(), "\nFile System:\n\n");
        fprintf(fp.get(), "   Type   |              Name              | Length |  LBA  |   Bytes   |   Source File\n");

        int layer = 0;
        iso::layerBegLBA = 0;
        for (const auto &[entries, layerLenLBA, _] : layers)
        {
            fprintf(fp.get(), "\n    Layer%d:\n", layer++);
            iso::DirTree *dirTree = entries.front().subdir.get();
            dirTree->SortDirectoryEntries(true);
            dirTree->OutputLBAlisting(fp.get(), 0);
            dirTree->SortDirectoryEntries();
            iso::layerBegLBA += layerLenLBA - layout::LBA_ISO_PVD;
        }

        if (!param::quietMode)
            printf("Wrote file LBA log \"%s\"\n\n", param::lbaFile.string().c_str());
    }
    else if (!param::quietMode)
    {
        printf("Failed to write LBA log \"%s\"!\n\n", param::lbaFile.string().c_str());
    }
}

static void WriteLogHead(const std::list<std::tuple<std::list<Entry>, uint32_t, uint32_t>> &layers)
{
    unique_file fp = OpenScopedFile(param::lbaHeadFile, "w");
    if (fp != nullptr)
    {
        fprintf(fp.get(), "#ifndef _ISO_FILES\n");
        fprintf(fp.get(), "#define _ISO_FILES\n\n");

        int layer = 0;
        iso::layerBegLBA = 0;
        for (const auto &[entries, layerLenLBA, _] : layers)
        {
            fprintf(fp.get(), "/* LAYER%d */\n", layer++);
            iso::DirTree *dirTree = entries.front().subdir.get();
            dirTree->SortDirectoryEntries(true);
            dirTree->OutputHeaderListing(fp.get(), "<ROOT>");
            dirTree->SortDirectoryEntries();
            iso::layerBegLBA += layerLenLBA - layout::LBA_ISO_PVD;
        }
        fprintf(fp.get(), "#endif\n");

        if (!param::quietMode)
            printf("Wrote file LBA listing header \"%s\"\n\n", param::lbaHeadFile.string().c_str());
    }
    else if (!param::quietMode)
    {
        printf("Failed to write LBA listing header \"%s\"!\n\n", param::lbaHeadFile.string().c_str());
    }
}

static void genCipherHashes(const char *serial, int &key, int &magic1, int &magic2)
{
    uint32_t letters = 0;
    uint32_t numbers = 0;

    // Pack ASCII code in reverse order
    for (int i = 0; *serial != 0 && i < 4; ++i, ++serial)
        letters |= static_cast<uint32_t>(*serial) << (21 - (i * 7));

    // Skip hyphen character
    if (*serial == '-' || *serial == '_')
        ++serial;

    // Parse string as a Base-10 integer
    for (int i = 0; *serial != 0 && i < 5; ++i, ++serial)
        numbers = (numbers * 10) + (*serial - '0');

    // Hash generation logic
    key    = ((numbers <<  3) & 0xF8) | ((letters >> 25) & 0x07);
    magic1 = ( numbers >> 10        ) | ( letters <<  7);
    magic2 = ((numbers >>  2) & 0xF8) | 0x04;
}

static bool BuildISO(xml::Reader &xml)
{
    std::string serial;
    Region::Bit region = Region::Undef;
    if (xml.ReadHeaders(serial, region) == nullptr)
        return false;

    if (param::volid_override)
        iso::isoIdentifiers.VolumeID = param::volid_override->c_str();

    // Print out identifiers if present
    if (!param::quietMode)
    {
        printf("Building ISO Image: \"%s\"\n\n", param::isoFile.string().c_str());

        printf("Identifiers:\n");

        if (iso::isoIdentifiers.SystemID != nullptr)
            printf("  System ID         : %s\n", iso::isoIdentifiers.SystemID);
        else
            printf("  System ID         : %s%s\n", iso::isoIdentifiers.SystemID = "PLAYSTATION", " (default)"); // Set default identifier if not present

        if (iso::isoIdentifiers.VolumeID != nullptr)
            printf("  Volume ID         : %s\n", iso::isoIdentifiers.VolumeID);

        if (iso::isoIdentifiers.VolumeSet != nullptr)
            printf("  Volume Set ID     : %s\n", iso::isoIdentifiers.VolumeSet);

        if (iso::isoIdentifiers.Publisher != nullptr)
            printf("  Publisher ID      : %s\n", iso::isoIdentifiers.Publisher);

        if (iso::isoIdentifiers.DataPreparer != nullptr)
            printf("  Data Preparer ID  : %s\n", iso::isoIdentifiers.DataPreparer);

        if (iso::isoIdentifiers.Application != nullptr)
            printf("  Application ID    : %s\n", iso::isoIdentifiers.Application);
        else
            printf("  Application ID    : %s%s\n", iso::isoIdentifiers.Application = "PLAYSTATION", " (default)"); // Set default identifier if not present

        if (iso::isoIdentifiers.Copyright != nullptr)
            printf("  Copyright ID      : %s\n", iso::isoIdentifiers.Copyright);

        if (iso::isoIdentifiers.CreationDate != nullptr)
            printf("  Creation Date     : %s\n", iso::isoIdentifiers.CreationDate);

        if (iso::isoIdentifiers.ModificationDate != nullptr)
            printf("  Modification Date : %s\n", iso::isoIdentifiers.ModificationDate);

        printf("\n");

        // If empty, blank sectors will be written.
        if (!param::logoRawFile.empty())
            printf("Logo file: \"%s\"\n\n", param::logoRawFile.string().c_str());
    }

    std::list<std::tuple<std::list<Entry>, uint32_t, uint32_t>> layers;
    while (xml.NextLayerElement())
    {
        // Parse directory entries in the <directory_tree> element
        if (!param::quietMode)
            printf("Parsing Layer%zu directory tree...\n", layers.size());

        // Generate file system
        auto &[entries, layerLenLBA, partitionStartLBA] = layers.emplace_back();
        iso::DirTree *dirTree = xml.ReadDirTree(entries);
        if (dirTree == nullptr)
            return false;

        // Sort entries
        dirTree->PartitionEntries();
        dirTree->SortDirectoryEntries();
        dirTree->SaveDirEntriesOrder();

        // Calculate tree LBAs
        const uint32_t pathTableLen = dirTree->CalculatePathTableLen(entries.front());
        const uint32_t isoRootLBA   = layout::LBA_TABLE_START + (GetSizeInSectors(pathTableLen) * 4);
        partitionStartLBA           = dirTree->CalculateDirRecordLBA(isoRootLBA);
        const uint32_t fidRootLBA   = partitionStartLBA + GetSizeInSectors(sizeof(layout::FSD));
        const uint32_t icbRootLBA   = dirTree->CalculateFileIdDescLBA(fidRootLBA);
        const uint32_t dataStartLBA = dirTree->CalculateInfCtrlBlockLBA(icbRootLBA);
        layerLenLBA                 = AlignTo<16>(dirTree->CalculateFileTreeLBA(dataStartLBA) + GetSizeInSectors(sizeof(anchorVolDescPtr)));

        if (!param::quietMode)
        {
            printf("  Files Total: %u\n", dirTree->GetFileCount());
            printf("  Directories: %u\n", dirTree->GetDirCount());
            printf("  Total file system size: %ju bytes (%u sectors)\n\n", static_cast<uintmax_t>(layerLenLBA) * DVD_SECTOR_SIZE, layerLenLBA);
        }
        iso::layerBegLBA += layerLenLBA - layout::LBA_ISO_PVD;
    }

    if (layers.empty())
    {
        printf("Error: No <%s> element found in XML.\n", xml::elem::LAYER);
        return false;
    }

    if (!param::lbaFile.empty())
        WriteLogLBA(layers);

    if (!param::lbaHeadFile.empty())
        WriteLogHead(layers);

    if (param::noIsoGen)
    {
        if (!param::quietMode)
            printf("Skipped image generation.\n");
        return true;
    }

    if (!param::overwrite && !param::noWarns && GetSize(param::isoFile) >= 0)
    {
        printf("WARNING: ISO image already exists, overwrite? <Y/n> ");
        uint8_t key = getchar();
        if (std::tolower(key) == 'n')
            return false;
        printf("\n");
    }

    // Create ISO image for writing
    if (!dvd::writer->Create(param::isoFile, iso::layerBegLBA + layout::LBA_ISO_PVD))
    {
        printf("ERROR: Cannot open or create output image file.\n");
        return false;
    }

    // Write files
    if (!param::quietMode)
        printf("Repacking...\n");

    iso::layerBegLBA = 0;
    for (const auto &[entries, layerLenLBA, _] : layers)
    {
        // Copy the files into the disc image
        entries.front().subdir.get()->WriteFiles();
        iso::layerBegLBA += layerLenLBA - layout::LBA_ISO_PVD;
    }
    if (!param::quietMode)
        printf("\n");

    // Generate encryption hashes from serial
    int key, magic1, magic2;
    genCipherHashes(serial.c_str(), key, magic1, magic2);

    // Write logo data
    if (!param::quietMode)
        printf("Writing logo data...");

    iso::WriteBootLogo(region, key);

    if (!param::quietMode)
        printf("Ok.\n");

    // Master Disc sectors
    auto masterSectors = dvd::writer->GetSectorView(14, 2);
    masterSectors->WriteBlankSectors(2); // TODO: conditionally write actual MD data

    // Write file system
    if (!param::quietMode)
        printf("Writing descriptors... ");

    iso::layerBegLBA = 0;
    for (const auto &[entries, layerLenLBA, partitionStartLBA] : layers)
    {
        iso::DirTree *dirTree = entries.front().subdir.get();

        // Write ISO descriptors
        dirTree->WriteIsoDescriptors(layerLenLBA);
        dirTree->WriteDirectoryRecords();

        // Write Extended Area Descriptors
        iso::WriteExtendedDescriptors();

        // Write UDF descriptors
        uint32_t partitionSize = layerLenLBA - GetSizeInSectors(sizeof(anchorVolDescPtr)) - partitionStartLBA;
        iso::WriteUdfDescriptors(partitionStartLBA, partitionSize, layout::LBA_UDF_MAIN);
        iso::WriteUdfDescriptors(partitionStartLBA, partitionSize, layout::LBA_UDF_RSRV);
        iso::WriteLviDescriptors(dirTree, partitionSize);
        iso::WriteAnchorDescriptor(partitionStartLBA + partitionSize);

        // Write file system descriptors to finish the layer
        dirTree->WriteInfoCtrlBlocks(partitionStartLBA);
        dirTree->WriteFileSetDescriptors(partitionStartLBA);
        dirTree->WriteFileIdDescriptors(partitionStartLBA);

        iso::layerBegLBA += layerLenLBA - layout::LBA_ISO_PVD;
    }
    if (!param::quietMode)
        printf("Ok.\n\n");

    // Close ISO writer
    dvd::writer->Close();

    if (!param::quietMode)
        printf("Image built successfully.\n");

    return true;
}

int Main(int argc, char *argv[])
{
    constexpr const char *HELP_TEXT =
        "Usage: mkps2iso [options] <input>\n\n"
        "  <input>\t\tAny XML project file defining the disc layout to build.\n\n"
        "Options:\n"
        "  -h|--help\t\tShows this help text\n"
        "  -q|--quiet\t\tQuiet mode (suppress all but warnings and errors)\n"
        "  -w|--warns\t\tSuppress all warnings (can be used along with -q)\n"
        "  -n|--noisogen\t\tDo not generate ISO, but calculate file LBA locations (for use with --lba or --lbahead)\n"
        "  -l|--lba <file>\tGenerate a log of file LBA locations in disc image\n"
        "  -lh|--lbahead <file>\tGenerate a C header of file LBA locations in disc image\n"
        "  -o|--output <file>\tSpecify output file (overrides image_name attribute)\n"
        "  -L|--logo <file>\tSpecify boot logo file (overrides file attribute)\n"
        "  -lb|--label <name>\tSpecify volume ID (overrides volume element)\n"
        "  -y\t\t\tAlways overwrite ISO image files\n";

    constexpr const char *VERSION_TEXT =
        "MKPS2ISO " VERSION " - PlayStation 2 Image Maker\n"
        "Get the latest version at https://github.com/N4gtan/mkps2iso\n\n";

    if (argc == 1)
    {
        printf(VERSION_TEXT);
        printf(HELP_TEXT);
        return EXIT_SUCCESS;
    }

    bool OutputOverride = false;
    // Parse arguments
    for (char **args = argv + 1; *args != nullptr; args++)
    {
        // Is it a switch?
        if ((*args)[0] == '-')
        {
            if (ParseArgument(args, "h", "help"))
            {
                printf(VERSION_TEXT);
                printf(HELP_TEXT);
                return EXIT_SUCCESS;
            }
            if (ParseArgument(args, "q", "quiet"))
            {
                param::quietMode = true;
                continue;
            }
            if (ParseArgument(args, "w", "warns"))
            {
                param::noWarns = true;
                continue;
            }
            if (ParseArgument(args, "n", "noisogen"))
            {
                param::noIsoGen = true;
                continue;
            }
            if (ParseArgument(args, "y"))
            {
                param::overwrite = true;
                continue;
            }
            if (auto lbaFile = ParsePathArgument(args, "l", "lba"); lbaFile.has_value())
            {
                if (CompareICase(lbaFile->extension().string(), ".xml"))
                {
                    args--;
                    param::lbaFile = lbaFile->stem() += "_LBA.txt";
                    continue;
                }
                param::lbaFile = lbaFile->lexically_normal();
                continue;
            }
            if (auto lbaHead = ParsePathArgument(args, "lh", "lbahead"); lbaHead.has_value())
            {
                if (CompareICase(lbaHead->extension().string(), ".xml"))
                {
                    args--;
                    param::lbaHeadFile = lbaHead->stem() += "_LBA.h";
                    continue;
                }
                param::lbaHeadFile = lbaHead->lexically_normal();
                continue;
            }
            if (auto output = ParsePathArgument(args, "o", "output"); output.has_value())
            {
                param::isoFile = output->lexically_normal();
                OutputOverride = true;
                continue;
            }
            if (auto output = ParsePathArgument(args, "L", "logo"); output.has_value())
            {
                param::logoRawFile = output->lexically_normal();
                continue;
            }
            if (auto label = ParseStringArgument(args, "lb", "label"); label.has_value())
            {
                param::volid_override = label;
                continue;
            }

            // If we reach this point, an unknown parameter was passed
            printf("Unknown parameter: %s\n", *args);
            return EXIT_FAILURE;
        }

        if (param::xmlFile.empty())
        {
            param::xmlFile = fs::path(*args).lexically_normal().lexically_proximate(fs::current_path());
        }
        else
        {
            printf("Only one XML script is supported. (use an XML with multiple <iso_project> elements instead)\n");
            return EXIT_FAILURE;
        }
    }

    if (param::xmlFile.empty())
    {
        printf("No XML script specified.\n");
        return EXIT_FAILURE;
    }

    if (!param::quietMode)
        printf(VERSION_TEXT);

    if (param::lbaFile == "-l" || param::lbaFile == "--lba")
        param::lbaFile = param::xmlFile.stem() += "_LBA.txt";

    if (param::lbaHeadFile == "-lh" || param::lbaHeadFile == "--lbahead")
        param::lbaHeadFile = param::xmlFile.stem() += "_LBA.h";

    // Initialize xml reader
    xml::Reader xml;

    // Initialize dvd writer
    dvd::writer = std::make_unique<dvd::IsoWriter>();

    int imagesCount = 0;
    // Build loop for XML scripts with multiple <iso_project> elements
    while (xml.NextProjectElement() != nullptr)
    {
        imagesCount++;
        if (imagesCount > 1 && OutputOverride)
        {
            printf("ERROR: -o switch cannot be used in a multi-disc ISO project.\n");
            return EXIT_FAILURE;
        }

        if (!BuildISO(xml))
            return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
